version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: backend-ci/Dockerfile
    command: ["bash", "/var/www/html/docker-start.sh"]
    ports:
      - "8000:80"
    env_file:
      - backend-ci/.env
    depends_on:
      - db
    volumes:
      - ./backend-ci:/var/www/html

  fe:
    build:
      context: ./lanocrm
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    volumes:
      - ./lanocrm:/app
      - /app/node_modules

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lanocrm_shop
      MYSQL_USER: lanocrm_user
      MYSQL_PASSWORD: KP7n4RjcDbedSE2W8GgA
    volumes:
      - db_data:/var/lib/mysql

  # MySQL test database (separate from dev)
  db-test:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lanocrm_test
      MYSQL_USER: lanocrm_user
      MYSQL_PASSWORD: KP7n4RjcDbedSE2W8GgA
    volumes:
      - test_db_data:/var/lib/mysql
    ports:
      - "3307:3306" # Different port to avoid conflict

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db,db-test
      PMA_USER: lanocrm_user
      PMA_PASSWORD: KP7n4RjcDbedSE2W8GgA
    ports:
      - "8080:80"
    depends_on:
      - db
      - db-test

volumes:
  db_data:
  test_db_data: # New volume for test data
