<?php
// Simple standalone test - find which method fails in migration

$methods = [
    'createBaseTables',
    'createCompanyScopeTables',
    'createProductTables',
    'createProductCategoryTables',
    'createProductVariantTables',
    'createProductImageTables',
    'createProductAttributeTables',
    'createProductAttributeOptionTables',
    'createProductAttributeValueTables',
    'createProductBatchTables',
    'createProductSerialNumberTables',
    'createDeliveryNoteTables',
    'createApprovalTables',
    'createStockLedgerTables',
    'createStockEntryTables',
    'createReorderPlanningTables',
    'createAdvancedPricingTables',
    'createPriceListTables',
    'createPriceListItemTables',
    'createPaymentMethodTables',
    'createTaxTemplateTables',
    'createLoyaltyTables',
    'createCouponTables',
    'createPurchaseOrderTables',
    'createPurchaseOrderItemTables',
    'createGoodsReceiptTables',
    'createLandedCostTables',
    'createSubcontractingTables',
    'createOrderTables',
    'createOrderItemTables',
    'createOrderPaymentTables',
    'createPaymentEntryTables',
    'createBankReconciliationTables',
    'createAccountingTables',
    'createOrderSequenceTables',
    'createPOSTables',
    'createPOSOfflineTables',
    'createLeadTables',
    'createOpportunityTables',
    'createQuotationTables',
    'createCampaignTables',
    'createSupportTables',
    'createContractTables',
    'createSalesInvoiceTables',
    'createPurchaseInvoiceTables',
    'createReturnTables',
    'createReturnItemTables',
    'createInvoiceTables',
    'createInvoiceOrderTables',
    'createInventoryStockTables',
    'createInventoryMovementTables',
    'createInventoryAlertTables',
    'createOrderStatusLogTables',
    'createWebhookTables',
    'createQualityTables',
    'createOrderTemplateTables',
    'createEcommerceTables',
    'createManufacturingTables',
    'createSubscriptionTables',
    'createCashTransactionTables', // <-- THIS IS THE TARGET
    'createAssetTables',
    'createPortalNotificationTables',
    'createHRPayrollTables',
    'createRegionalTaxTables',
    'createSchedulerTables',
    'createProjectTables',
];

echo "Migration has " . count($methods) . " methods to execute\n";
echo "createCashTransactionTables is at position " . (array_search('createCashTransactionTables', $methods) + 1) . "\n";
echo "\nTest DB shows only 35 tables were created\n";
echo "This suggests migration stopped before reaching createCashTransactionTables\n";
