<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'id' => 1,
                'product_type' => 'goods',
                'code' => 'TDH016',
                'barcode' => null,
                'name' => 'Túi đeo chéo da bò cao cấp khâu tay thủ công Lano TDH016',
                'slug' => 'tui-deo-cheo-da-bo-cao-cap-khau-tay-thu-cong-lano-tdh016-tdh016',
                'brand' => null,
                'unit' => 'Cái',
                'purchase_price' => 1500000,
                'selling_price' => 7500000,
                'wholesale_price' => null,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 1,
                'image' => 'https://cdn2-retail-images.kiotviet.vn/2025/10/19/lano/3fcf08b6f8b240fa99a661e56cdc7b3f.jpeg',
                'images' => '["https://cdn2-retail-images.kiotviet.vn/2025/10/19/lano/3fcf08b6f8b240fa99a661e56cdc7b3f.jpeg"]',
                'weight' => 0,
                'dimensions' => null,
                'description' => null,
                'content' => null,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-11-01 17:01:49',
            ],
            [
                'id' => 2,
                'product_type' => 'goods',
                'code' => 'VDNTK035',
                'barcode' => null,
                'name' => 'Ví da handmade khâu tay thủ công sang trọng lịch lãm Lano VDNTK035',
                'slug' => 'vi-da-handmade-khau-tay-thu-cong-sang-trong-lich-lam-lano-vdntk035-vdntk035',
                'brand' => null,
                'unit' => 'Cái',
                'purchase_price' => 650000,
                'selling_price' => 1950000,
                'wholesale_price' => null,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn2-retail-images.kiotviet.vn/2025/10/19/lano/9b9cf7569bd348fd9c73ab9c167a96b5.jpeg',
                'images' => '["https://cdn2-retail-images.kiotviet.vn/2025/10/19/lano/9b9cf7569bd348fd9c73ab9c167a96b5.jpeg"]',
                'weight' => 0,
                'dimensions' => null,
                'description' => null,
                'content' => null,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 3,
                'product_type' => 'goods',
                'code' => 'VDNTK034',
                'barcode' => null,
                'name' => 'Ví da epsom italia khâu thủ công nhỏ gọn tiện lợi Lano VDNTK034',
                'slug' => 'vi-da-epsom-italia-khau-thu-cong-nho-gon-tien-loi-lano-vdntk034-vdntk034',
                'brand' => null,
                'unit' => 'Cái',
                'purchase_price' => 350000,
                'selling_price' => 1500000,
                'wholesale_price' => null,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn2-retail-images.kiotviet.vn/2025/10/15/lano/677874c0246b4f93ab1843fb4ddab0a8.jpeg',
                'images' => '["https://cdn2-retail-images.kiotviet.vn/2025/10/15/lano/677874c0246b4f93ab1843fb4ddab0a8.jpeg"]',
                'weight' => 0,
                'dimensions' => null,
                'description' => null,
                'content' => null,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 4,
                'product_type' => 'goods',
                'code' => 'VCTK018',
                'barcode' => null,
                'name' => 'Ví cầm tay da bò togo cao cấp nhỏ gọn tiện lợi VCTK018',
                'slug' => 'vi-cam-tay-da-bo-togo-cao-cap-nho-gon-tien-loi-vctk018-vctk018',
                'brand' => null,
                'unit' => 'Cái',
                'purchase_price' => 850000,
                'selling_price' => 2150000,
                'wholesale_price' => null,
                'stock_quantity' => 1,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn2-retail-images.kiotviet.vn/2025/10/05/lano/4a78c71fcc864e8c8fca80ed0632d653.jpeg',
                'images' => '["https://cdn2-retail-images.kiotviet.vn/2025/10/05/lano/4a78c71fcc864e8c8fca80ed0632d653.jpeg"]',
                'weight' => 0,
                'dimensions' => null,
                'description' => null,
                'content' => null,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 5,
                'product_type' => 'goods',
                'code' => 'CLTK033',
                'barcode' => null,
                'name' => 'Túi Clutch handmade khâu tay thủ công da bò cao cấp Lano CLTK033',
                'slug' => 'tui-clutch-handmade-khau-tay-thu-cong-da-bo-cao-cap-lano-cltk033-cltk033',
                'brand' => null,
                'unit' => 'Cái',
                'purchase_price' => 1800000,
                'selling_price' => 6500000,
                'wholesale_price' => null,
                'stock_quantity' => 1,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn2-retail-images.kiotviet.vn/2025/09/26/lano/3244329e059a44579ded30fcdc36a8dc.jpeg',
                'images' => '["https://cdn2-retail-images.kiotviet.vn/2025/09/26/lano/3244329e059a44579ded30fcdc36a8dc.jpeg"]',
                'weight' => 0,
                'dimensions' => null,
                'description' => null,
                'content' => null,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 6,
                'product_type' => 'goods',
                'code' => 'TDH015',
                'barcode' => null,
                'name' => 'Túi tote da togo cao cấp khâu tay thủ công Lano TDH015',
                'slug' => 'tui-tote-da-togo-cao-cap-khau-tay-thu-cong-lano-tdh015-tdh015',
                'brand' => null,
                'unit' => 'Cái',
                'purchase_price' => 3000000,
                'selling_price' => 16000000,
                'wholesale_price' => null,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn-images.kiotviet.vn/2025/09/16/lano/033a78998b7a4325bc5a7b975661c779.jpeg',
                'images' => '["https://cdn-images.kiotviet.vn/2025/09/16/lano/033a78998b7a4325bc5a7b975661c779.jpeg"]',
                'weight' => 0,
                'dimensions' => null,
                'description' => null,
                'content' => null,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 7,
                'product_type' => 'goods',
                'code' => 'VDNT15',
                'name' => 'Ví da đựng thẻ khâu tay thủ công nhỏ gọn tiện lợi Lano VDNT15',
                'slug' => 'vi-da-dung-the-khau-tay-thu-cong-nho-gon-tien-loi-lano-vdnt15-vdnt15',
                'unit' => 'Cái',
                'purchase_price' => 350000,
                'selling_price' => 1250000,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn-images.kiotviet.vn/2025/09/12/lano/fd5e60ddc37448efa69c2fb2e33c61b1.jpeg',
                'images' => '["https://cdn-images.kiotviet.vn/2025/09/12/lano/fd5e60ddc37448efa69c2fb2e33c61b1.jpeg"]',
                'weight' => 0,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 8,
                'product_type' => 'goods',
                'code' => 'VCTK016',
                'name' => 'Ví cầm tay da bò togo chế tác theo yêu cầu Lano VCTK016',
                'slug' => 'vi-cam-tay-da-bo-togo-che-tac-theo-yeu-cau-lano-vctk016-vctk016',
                'unit' => 'Cái',
                'purchase_price' => 350000,
                'selling_price' => 1500000,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn-images.kiotviet.vn/2025/09/07/lano/bd44aa66a10e46f1aba6747fefed9021.jpeg',
                'images' => '["https://cdn-images.kiotviet.vn/2025/09/07/lano/bd44aa66a10e46f1aba6747fefed9021.jpeg"]',
                'weight' => 0,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 9,
                'product_type' => 'goods',
                'code' => 'TDH014',
                'name' => 'Túi tote da bò epsom cao cấp khâu tay thủ công Lano TDH014',
                'slug' => 'tui-tote-da-bo-epsom-cao-cap-khau-tay-thu-cong-lano-tdh014-tdh014',
                'unit' => 'Cái',
                'purchase_price' => 2500000,
                'selling_price' => 8000000,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn-images.kiotviet.vn/2025/09/06/lano/d5d88bf42fd3424a9aa3f5b1a21a8602.jpeg',
                'images' => '["https://cdn-images.kiotviet.vn/2025/09/06/lano/d5d88bf42fd3424a9aa3f5b1a21a8602.jpeg"]',
                'weight' => 0,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
            [
                'id' => 10,
                'product_type' => 'goods',
                'code' => 'TDH012',
                'name' => 'Túi Tote Da bò togo cao cấp Handmade Đựng Laptop 13inch Lano TDH012',
                'slug' => 'tui-tote-da-bo-togo-cao-cap-handmade-dung-laptop-13inch-lano-tdh012-tdh012',
                'unit' => 'Cái',
                'purchase_price' => 3000000,
                'selling_price' => 11000000,
                'stock_quantity' => 0,
                'alert_stock' => 10,
                'has_variants' => 0,
                'image' => 'https://cdn-images.kiotviet.vn/2025/09/05/lano/b2045e6828474d508ff86dd8427593f0.jpeg',
                'images' => '["https://cdn-images.kiotviet.vn/2025/09/05/lano/b2045e6828474d508ff86dd8427593f0.jpeg"]',
                'weight' => 0,
                'is_active' => 1,
                'is_available_online' => 1,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-10-27 09:31:56',
                'updated_at' => '2025-10-27 09:31:56',
            ],
        ];

        $categories = [
            ['id' => 1, 'parent_id' => null, 'level' => 1, 'code' => 'CAT_0001', 'name' => 'Túi da handmade', 'slug' => 'tui-da-handmade', 'description' => null, 'image' => null, 'sort_order' => 0, 'status' => 'active', 'created_at' => '2025-10-27 09:31:56', 'updated_at' => '2025-11-18 07:58:01'],
            ['id' => 2, 'parent_id' => null, 'level' => 1, 'code' => 'CAT_0002', 'name' => 'VÍ DA', 'slug' => 'vi-da', 'description' => null, 'image' => null, 'sort_order' => 0, 'status' => 'active', 'created_at' => '2025-10-27 09:31:56', 'updated_at' => '2025-11-18 07:58:01'],
            ['id' => 3, 'parent_id' => null, 'level' => 1, 'code' => 'CAT_0003', 'name' => 'TÚI DA NAM', 'slug' => 'tui-da-nam', 'description' => null, 'image' => null, 'sort_order' => 0, 'status' => 'active', 'created_at' => '2025-10-27 09:31:56', 'updated_at' => '2025-11-18 07:58:01'],
            ['id' => 15, 'parent_id' => 2, 'level' => 2, 'code' => 'CAT_0015', 'name' => 'Ví thiết kế', 'slug' => 'vi-thiet-ke', 'description' => null, 'image' => null, 'sort_order' => 0, 'status' => 'active', 'created_at' => '2025-10-27 09:31:56', 'updated_at' => '2025-11-18 08:03:18'],
            ['id' => 16, 'parent_id' => 3, 'level' => 2, 'code' => 'CAT_0016', 'name' => 'Túi Da Đeo Chéo', 'slug' => 'tui-da-deo-cheo', 'description' => null, 'image' => null, 'sort_order' => 0, 'status' => 'active', 'created_at' => '2025-10-27 09:31:56', 'updated_at' => '2025-11-18 07:58:01'],
            ['id' => 17, 'parent_id' => 3, 'level' => 2, 'code' => 'CAT_0017', 'name' => 'Túi đeo bụng', 'slug' => 'tui-deo-bung', 'description' => null, 'image' => null, 'sort_order' => 0, 'status' => 'active', 'created_at' => '2025-10-27 09:31:56', 'updated_at' => '2025-11-18 07:58:01'],
        ];

        $links = [
            ['product_id' => 1, 'category_id' => 1],
            ['product_id' => 2, 'category_id' => 2],
            ['product_id' => 3, 'category_id' => 2],
            ['product_id' => 4, 'category_id' => 2],
            ['product_id' => 5, 'category_id' => 1],
            ['product_id' => 6, 'category_id' => 1],
            ['product_id' => 7, 'category_id' => 2],
            ['product_id' => 8, 'category_id' => 2],
            ['product_id' => 9, 'category_id' => 1],
            ['product_id' => 10,'category_id' => 1],
        ];

        // insert data
        $this->db->table('product_categories')->ignore(true)->insertBatch($categories);
        $this->db->table('products')->ignore(true)->insertBatch($products);
        $this->db->table('product_category_links')->ignore(true)->insertBatch($links);
    }
}
