import React, { useState, useEffect, useCallback } from 'react';
import { Modal, Radio, Input, Select, Button, App } from 'antd';
import deliveryPartnerApi from '../../api/deliveryPartnerApi';
import styles from './DeliveryPartnerModal.module.css';

// Partner groups - can be fetched from API later
const PARTNER_GROUPS = [
    { value: 'nhan_vien', label: 'Nhân viên nội bộ' },
    { value: 'doi_tac', label: 'Đối tác bên ngoài' },
    { value: 'grab', label: 'Grab' },
    { value: 'ghn', label: 'Giao hàng nhanh' },
];

const DeliveryPartnerModal = ({ open, onClose, onSave, mode = 'add', partnerData = null }) => {
    const { message } = App.useApp();
    const [loading, setLoading] = useState(false);
    const [formData, setFormData] = useState({
        partnerType: 'individual',
        partnerCode: '',
        name: '',
        phone: '',
        email: '',
        addressDetail: '',
        province: '',
        district: '',
        ward: '',
        partnerGroup: null,
        note: '',
    });

    // Reset form when modal opens
    useEffect(() => {
        if (!open) return;

        if (mode === 'add') {
            // Reset form with empty values - backend will generate code
            setFormData({
                partnerType: 'individual',
                partnerCode: '', // Will be auto-generated by backend
                name: '',
                phone: '',
                email: '',
                addressDetail: '',
                province: '',
                district: '',
                ward: '',
                partnerGroup: null,
                note: '',
            });
        } else if (mode === 'edit' && partnerData) {
            // Fill form with existing partner data
            setFormData({
                id: partnerData.id,
                partnerType: partnerData.partnerType || partnerData.type || 'individual',
                partnerCode: partnerData.partnerCode || partnerData.code || '',
                name: partnerData.name || '',
                phone: partnerData.phone || '',
                email: partnerData.email || '',
                addressDetail: partnerData.addressDetail || partnerData.address || '',
                province: partnerData.province || partnerData.city || '',
                district: partnerData.district || '',
                ward: partnerData.ward || '',
                partnerGroup: partnerData.partnerGroup || partnerData.group_name || null,
                note: partnerData.note || '',
            });
        }
    }, [mode, partnerData, open]);

    const handleChange = useCallback((field, value) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    }, []);

    const handleSave = async () => {
        // Validate required fields
        if (!formData.name?.trim()) {
            message.error('Vui lòng nhập tên đối tác');
            return;
        }

        setLoading(true);
        try {
            const payload = {
                code: formData.partnerCode || undefined,
                name: formData.name,
                contact_person: formData.name,
                phone: formData.phone || undefined,
                email: formData.email || undefined,
                address: formData.addressDetail || undefined,
                city: formData.province || undefined,
                status: 'active',
            };

            let response;
            if (mode === 'edit' && formData.id) {
                response = await deliveryPartnerApi.update(formData.id, payload);
            } else {
                response = await deliveryPartnerApi.create(payload);
            }

            if (response.success) {
                message.success(mode === 'add' ? 'Thêm đối tác thành công' : 'Cập nhật đối tác thành công');
                onSave?.(response.data);
                onClose?.();
            } else {
                message.error(response.message || 'Lỗi khi lưu đối tác');
            }
        } catch (error) {
            console.error('Save delivery partner error:', error);
            message.error(error.response?.data?.message || 'Lỗi khi lưu đối tác');
        } finally {
            setLoading(false);
        }
    };

    const title = mode === 'add' ? 'Thêm đối tác giao hàng' : 'Sửa thông tin đối tác';

    return (
        <Modal
            title={title}
            open={open}
            onCancel={onClose}
            width={600}
            footer={
                <div className={styles.modalFooter}>
                    <Button onClick={onClose}>Bỏ qua</Button>
                    <Button type="primary" onClick={handleSave} loading={loading}>Lưu</Button>
                </div>
            }
            className={styles.modal}
        >
            <div className={styles.form}>
                {/* Partner Type */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Loại đối tác</label>
                    <Radio.Group
                        value={formData.partnerType}
                        onChange={(e) => handleChange('partnerType', e.target.value)}
                    >
                        <Radio value="individual">Cá nhân</Radio>
                        <Radio value="company">Công ty</Radio>
                    </Radio.Group>
                </div>

                {/* Partner Code */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Mã đối tác</label>
                    <Input
                        value={formData.partnerCode}
                        placeholder={mode === 'add' ? 'Mã tự động' : ''}
                        onChange={(e) => handleChange('partnerCode', e.target.value)}
                        className={styles.input}
                        disabled={mode === 'edit'}
                    />
                </div>

                {/* Partner Name */}
                <div className={styles.formRow}>
                    <label className={styles.label}>
                        Tên đối tác<span className={styles.required}>*</span>
                    </label>
                    <Input
                        value={formData.name}
                        onChange={(e) => handleChange('name', e.target.value)}
                        className={styles.input}
                    />
                </div>

                {/* Phone */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Điện thoại</label>
                    <Input
                        value={formData.phone}
                        onChange={(e) => handleChange('phone', e.target.value)}
                        className={styles.input}
                    />
                </div>

                {/* Email */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Email</label>
                    <Input
                        value={formData.email}
                        onChange={(e) => handleChange('email', e.target.value)}
                        className={styles.input}
                    />
                </div>

                {/* Address Detail */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Địa chỉ chi tiết</label>
                    <Input
                        value={formData.addressDetail}
                        placeholder="Số nhà, tòa nhà, ngõ, đường"
                        onChange={(e) => handleChange('addressDetail', e.target.value)}
                        className={styles.input}
                    />
                </div>

                {/* Province/District */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Tỉnh/TP - Quận/Huyện</label>
                    <Input
                        value={formData.province}
                        onChange={(e) => handleChange('province', e.target.value)}
                        className={styles.input}
                    />
                </div>

                {/* Ward */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Phường/Xã</label>
                    <Input
                        value={formData.ward}
                        onChange={(e) => handleChange('ward', e.target.value)}
                        className={styles.input}
                    />
                </div>

                {/* Partner Group */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Nhóm đối tác</label>
                    <Select
                        value={formData.partnerGroup}
                        placeholder="Chọn nhóm đối tác"
                        onChange={(val) => handleChange('partnerGroup', val)}
                        options={PARTNER_GROUPS}
                        className={styles.select}
                        allowClear
                    />
                </div>

                {/* Note */}
                <div className={styles.formRow}>
                    <label className={styles.label}>Ghi chú</label>
                    <Input.TextArea
                        value={formData.note}
                        onChange={(e) => handleChange('note', e.target.value)}
                        className={styles.input}
                        rows={2}
                    />
                </div>
            </div>
        </Modal>
    );
};

export default DeliveryPartnerModal;
